version: 1.0.0
website: https://microrun.org
bootstrap: true
build:
  - echo "Nothing to do"
install:
  - mkdir -p /target/usr/{lib,bin}
  - mkdir /target/{etc,tmp}
  - ln -s ./usr/bin /target/bin
  - ln -s ./usr/lib /target/lib
  - ln -s ./usr/lib /target/lib64
  - ls /target
  - |
    cat > /target/etc/passwd << "EOF"
    root:x:0:0:root:/root:/bin/bash
    nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
    EOF
    
    cat > /target/etc/group << "EOF"
    root:x:0:
    bin:x:1:
    sys:x:2:
    kmem:x:3:
    tty:x:4:
    tape:x:5:
    daemon:x:6:
    floppy:x:7:
    disk:x:8:
    lp:x:9:
    dialout:x:10:
    audio:x:11:
    video:x:12:
    utmp:x:13:
    usb:x:14:
    cdrom:x:15:
    EOF